#TASK 2-SUM OF FIRST 10 NUMBERS USING RECURSVIE FUNCTION

print("<---- PRABAL MANHAS | 20BCS4513 | WS ALLOTTED - 5 ---->")
def task2_prabal(n):
#IF NUMBER IS LESS THAN 1 IT WILL RUN THE PROGRAM AND RETURN THE VALUE
   if n <= 1:
       return n
   else:
#IF NUMBER IS GREATER THAN 1 IT WILL FIND THE SUM UPTO THE ENTERED NUMBER USING RECURSION
       return n + task2_prabal(n-1)

# CALCULATING THE SUM FOR THE FIRST 10 NUMBERS
inputnum = 10
# AS I AM FINDING SUM FOR NUMBERS RANGING FROM 0-10
print("THE SUM OF NUMBERS FROM 0 - 10 = ",task2_prabal(inputnum))
# PRINTING THE FINAL SUM RESULT AND CALLING THE FUNCTION
print("CLASS - 20IOT GROUP-A")
# PRINTING CLASS AND GROUP